# Generated by Django 3.2.7 on 2021-09-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsblock',
            name='source_id',
        ),
        migrations.AddField(
            model_name='newsblock',
            name='title',
            field=models.CharField(default='0', max_length=200, verbose_name='Заголовок статьи'),
        ),
        migrations.AlterField(
            model_name='newsblock',
            name='source_name',
            field=models.CharField(default='0', max_length=20, verbose_name='Название источника'),
        ),
        migrations.AlterField(
            model_name='newsblock',
            name='source_url',
            field=models.CharField(default='0', max_length=100, verbose_name='Ссылка'),
        ),
    ]
