# Generated by Django 3.2.7 on 2021-09-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210914_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsblock',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.RemoveField(
            model_name='newsblock',
            name='source_name',
        ),
        migrations.AddField(
            model_name='newsblock',
            name='source_favicon',
            field=models.CharField(default='0', max_length=200, verbose_name='Логотип издания'),
        ),
    ]
