# Generated by Django 3.2.7 on 2021-09-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_newsblock_source_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(default=0, verbose_name='Идентификатор источника')),
                ('source_favicon', models.CharField(default='0', max_length=200, verbose_name='Логотип издания')),
                ('soutce_name', models.CharField(default='0', max_length=20, verbose_name='Название источника')),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
            },
        ),
    ]
