# Generated by Django 3.2.7 on 2021-09-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='soutce_name',
            new_name='source_name',
        ),
        migrations.AddField(
            model_name='source',
            name='source_name_form',
            field=models.CharField(default='0', max_length=20, verbose_name='Название источника для формы'),
        ),
    ]
