# Generated by Django 3.2.7 on 2021-10-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211006_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followed_sources',
            field=models.ManyToManyField(to='main.Source'),
        ),
    ]
