# Generated by Django 3.2.7 on 2021-10-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_user_followed_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_notification',
            field=models.BooleanField(default=False, verbose_name='Отправлять уведомления?'),
        ),
    ]
