# Generated by Django 3.2.7 on 2021-10-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_user_telegram_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsblock',
            name='new',
            field=models.BooleanField(default=True, verbose_name='Отправлять уведомление'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_userid',
            field=models.CharField(default='0', max_length=20, verbose_name='Логин'),
        ),
    ]
