# Generated by Django 3.2.7 on 2022-11-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20211009_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsblock',
            name='source_favicon',
            field=models.CharField(blank=True, default='0', max_length=200, verbose_name='Логотип издания'),
        ),
        migrations.AlterField(
            model_name='newsblock',
            name='source_id',
            field=models.IntegerField(blank=True, default=0, verbose_name='Идентификатор источника'),
        ),
        migrations.AlterField(
            model_name='newsblock',
            name='source_url',
            field=models.CharField(blank=True, default='0', max_length=200, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='newsblock',
            name='views_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='Кол-во просмотров'),
        ),
    ]
