# Generated by Django 3.2.7 on 2022-11-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20221129_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsblock',
            name='source_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Идентификатор источника'),
        ),
        migrations.AlterField(
            model_name='newsblock',
            name='views_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Кол-во просмотров'),
        ),
    ]
